name: Front
# This is a trigger for any push to the repo
on:
  push:
    branches:
      - main
      - develop
    paths:
      - /frontend/frontend/**

jobs:
  react_test_and_lint:
    name: Test and Lint React app
    runs-on: self-hosted
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup Node.js 
        uses: actions/setup-node@v2 
        with: 
          node-version: '20.3.1' 
 
      # - name: Restore cached dependencies 
      #   id: cache-restore 
      #   uses: actions/cache@v3 
      #   with: 
      #     path: ./src/node_modules 
      #     key: npm-${{ hashFiles('./src/package-lock.json') }} 

      - name: Install dependencies 
        # if: steps.cache-restore.outputs.cache-hit != 'true' 
        run: |
          cd frontend
          npm ci - ignore-scripts
        
      #- name: Test with Jest
       # run: |
        #  pwd
         # cd frontend
          #npm run test

      - name: Eslint
        run: |
          pwd
          cd frontend
          npm run lint
